import fs from 'fs';
import path from 'path';
import { MarkdownRenderer } from '../chateraise/MarkdownRenderer';

export const metadata = {
  title: 'Dior アディクト グラス リップスティック SNS戦略提案',
  description: 'Dior アディクト グラス リップスティック SNS戦略提案 - 競合分析・ターゲット・コミュニケーション戦略',
};

export default function DiorSnsPage() {
  const filePath = path.join(process.cwd(), 'content', 'dior-sns-strategy.md');
  const markdown = fs.readFileSync(filePath, 'utf-8');

  return (
    <div className="min-h-screen bg-gray-50">
      {/* Header */}
      <header className="bg-gradient-to-r from-gray-900 to-gray-700 text-white">
        <div className="max-w-4xl mx-auto px-4 py-10">
          <p className="text-gray-300 text-sm mb-2">SNS戦略提案書</p>
          <h1 className="text-3xl md:text-4xl font-bold mb-3">
            Dior アディクト グラス リップスティック
          </h1>
          <p className="text-gray-300">
            SNS戦略提案 | 予算: 1,200万円 | 発売日: 2026年5月1日
          </p>
        </div>
      </header>

      {/* Content */}
      <main className="max-w-4xl mx-auto px-4 py-8">
        <div className="bg-white rounded-2xl shadow-sm border border-gray-100 px-6 md:px-10 py-8">
          <MarkdownRenderer content={markdown} />
        </div>
      </main>

      {/* Footer */}
      <footer className="bg-gray-800 text-gray-400 py-6 mt-12">
        <div className="max-w-4xl mx-auto px-4 text-center text-sm">
          <p>Dior アディクト グラス リップスティック SNS戦略提案</p>
          <p className="mt-1 text-gray-500">Generated by Claude Code | 2026年2月</p>
        </div>
      </footer>
    </div>
  );
}
