import fs from 'fs';
import path from 'path';
import { MarkdownRenderer } from './MarkdownRenderer';

export const metadata = {
  title: 'シャトレーゼ インドネシア市場分析レポート',
  description: 'シャトレーゼのインドネシア市場における競合分析・CEP分析・口コミ分析レポート',
};

export default function ChateraisePage() {
  const filePath = path.join(process.cwd(), 'content', 'chateraise-report.md');
  const markdown = fs.readFileSync(filePath, 'utf-8');

  return (
    <div className="min-h-screen bg-gray-50">
      {/* Header */}
      <header className="bg-gradient-to-r from-rose-600 to-orange-500 text-white">
        <div className="max-w-4xl mx-auto px-4 py-10">
          <p className="text-rose-100 text-sm mb-2">市場分析レポート</p>
          <h1 className="text-3xl md:text-4xl font-bold mb-3">
            シャトレーゼ インドネシア市場分析
          </h1>
          <p className="text-rose-100">
            作成日: 2026年2月5日 | フレームワーク: 市場 → プレイヤー → 顧客
          </p>
        </div>
      </header>

      {/* Content */}
      <main className="max-w-4xl mx-auto px-4 py-8">
        <div className="bg-white rounded-2xl shadow-sm border border-gray-100 px-6 md:px-10 py-8">
          <MarkdownRenderer content={markdown} />
        </div>
      </main>

      {/* Footer */}
      <footer className="bg-gray-800 text-gray-400 py-6 mt-12">
        <div className="max-w-4xl mx-auto px-4 text-center text-sm">
          <p>シャトレーゼ インドネシア市場分析レポート</p>
          <p className="mt-1 text-gray-500">Generated by Claude Code | 2026年2月5日</p>
        </div>
      </footer>
    </div>
  );
}
